Repository Chit-Chat-Org/chit-chat-nextjs, pull requests merged in 2024-05, with the labels that each got.

#15 Made changes in responsive design
  src/app/page.tsx
Labels: Level1, gssoc

#22 added 'required' class for the required fields and updated css
  src/app/globals.css
  src/app/login/page.tsx
  src/app/organization/page.tsx
  src/app/sign-up/page.tsx
Labels: enhancement, level1, gssoc

#24 Added pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement, level1

#32 Created contributing.md
  contributing.md
Labels: documentation, level1, gssoc
