Repository Chit-Chat-Org/chit-chat-nextjs, pull requests merged in 2024-06, with the labels that each got.

#40 added preloader
  package-lock.json
  package.json
  src/app/animation/preloaderAnimation.json
  src/app/page.tsx
Labels: enhancement, level2, gssoc

#39 Update Prompt.tsx
  src/app/Components/Prompt.tsx
Labels: enhancement, level1, gssoc

#33 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-pr-merge.yml
Labels: enhancement, level1, gssoc

#34 Added documentation issues template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: documentation, level1, gssoc

#44 add password visibility toggle in login and signup
  src/app/login/page.tsx
  src/app/sign-up/page.tsx
Labels: enhancement, level2, gssoc
